#!/bash/sh

sudo apt-get update

#Install PIP
sudo apt-get install python-pip python-dev build-essential 
sudo pip install --upgrade pip 
sudo pip install --upgrade virtualenv 

#Install Euclid and Future
sudo pip install euclid
sudo pip install future

#Install IPython
sudo pip install ipython[all]

#Install matplotlib
sudo apt-get install python-matplotlib

#Install feh for view images
sudo apt-get install feh

echo "Complete!"
